@baseUrl = http://localhost:8080/api


### Login ADMIN
# @name loginAdmin
POST http://localhost:8080/auth/login
Content-Type: application/json

{ "nomeUsuario": "admin", "senha": "123456" }

###
# ASSOCIAR CREDENCIAL VALIDA
POST {{baseUrl}}/usuarios/1/credenciais
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "credencialId": 1
}

###

# ASSOCIAR CREDENCIAL INEXISTENTE
POST {{baseUrl}}/usuarios/1/credenciais
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "credencialId": 999999
}

###

# ASSOCIAR CREDENCIAL COM USUARIO INEXISTENTE
POST {{baseUrl}}/usuarios/999999/credenciais
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "credencialId": 1
}

###

# ASSOCIAR CREDENCIAL COM ID NULO
POST {{baseUrl}}/usuarios/1/credenciais
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "credencialId": null
}

###

# ASSOCIAR CREDENCIAL SEM ID
POST {{baseUrl}}/usuarios/1/credenciais
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{}

###

# ASSOCIAR CREDENCIAL COM JSON INVALIDO
POST {{baseUrl}}/usuarios/1/credenciais
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "credencialId": 1,
}

###

# ASSOCIAR CREDENCIAL COM CONTENT TYPE INVALIDO
POST {{baseUrl}}/usuarios/1/credenciais
Content-Type: text/plain
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "credencialId": 1
}

###

# ASSOCIAR CREDENCIAL COM ID STRING
POST {{baseUrl}}/usuarios/1/credenciais
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "credencialId": "abc"
}

###

# ASSOCIAR CREDENCIAL COM ID NEGATIVO
POST {{baseUrl}}/usuarios/1/credenciais
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "credencialId": -1
}

###
GET {{baseUrl}}/usuarios/2
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# DESASSOCIAR CREDENCIAL VALIDA
DELETE {{baseUrl}}/usuarios/2/credenciais/2
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# DESASSOCIAR CREDENCIAL INEXISTENTE
DELETE {{baseUrl}}/usuarios/1/credenciais/999999
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# DESASSOCIAR CREDENCIAL DE USUARIO INEXISTENTE
DELETE {{baseUrl}}/usuarios/999999/credenciais/1
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# DESASSOCIAR CREDENCIAL COM ID INVALIDO
DELETE {{baseUrl}}/usuarios/1/credenciais/abc
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# DESASSOCIAR CREDENCIAL COM USUARIO INVALIDO
DELETE {{baseUrl}}/usuarios/abc/credenciais/1
Authorization: Bearer {{loginAdmin.response.body.token}}