@baseUrl = http://localhost:8080/api

### Login ADMIN
# @name loginAdmin
POST http://localhost:8080/auth/login
Content-Type: application/json

{ "nomeUsuario": "admin", "senha": "123456" }

###
# DOCUMENTO

###
# LISTAR DOCUMENTO OK
GET {{baseUrl}}/documentos
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# BUSCAR DOCUMENTO EXISTENTE OK
GET {{baseUrl}}/documentos/2
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# ASSOCIAR DOCUMENTO VALIDO
POST {{baseUrl}}/usuarios/2/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "documentoId": 2
}

###

# ASSOCIAR DOCUMENTO INEXISTENTE
POST {{baseUrl}}/usuarios/1/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "documentoId": 999999
}

###

# ASSOCIAR DOCUMENTO COM USUARIO INEXISTENTE
POST {{baseUrl}}/usuarios/999999/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "documentoId": 1
}

###

# ASSOCIAR DOCUMENTO COM ID NULO
POST {{baseUrl}}/usuarios/1/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "documentoId": null
}

###

# ASSOCIAR DOCUMENTO SEM ID
POST {{baseUrl}}/usuarios/1/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{}

###

# ASSOCIAR DOCUMENTO COM JSON INVALIDO
POST {{baseUrl}}/usuarios/1/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "documentoId": 1,
}

###

# ASSOCIAR DOCUMENTO COM CONTENT TYPE INVALIDO
POST {{baseUrl}}/usuarios/1/documentos
Content-Type: text/plain
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "documentoId": 1
}

###

# ASSOCIAR DOCUMENTO COM ID STRING
POST {{baseUrl}}/usuarios/1/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "documentoId": "abc"
}

###

# ASSOCIAR DOCUMENTO COM ID NEGATIVO
POST {{baseUrl}}/usuarios/1/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "documentoId": -1
}

###
GET {{baseUrl}}/usuarios/1
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# DESASSOCIAR DOCUMENTO VALIDO
DELETE {{baseUrl}}/usuarios/1/documentos/2
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# DESASSOCIAR DOCUMENTO INEXISTENTE
DELETE {{baseUrl}}/usuarios/1/documentos/999999
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# DESASSOCIAR DOCUMENTO DE USUARIO INEXISTENTE
DELETE {{baseUrl}}/usuarios/999999/documentos/1
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# DESASSOCIAR DOCUMENTO COM ID INVALIDO
DELETE {{baseUrl}}/usuarios/1/documentos/abc
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# DESASSOCIAR DOCUMENTO COM USUARIO INVALIDO
DELETE {{baseUrl}}/usuarios/abc/documentos/1
Authorization: Bearer {{loginAdmin.response.body.token}}