@baseUrl = http://localhost:8080/api

### Login ADMIN
# @name loginAdmin
POST http://localhost:8080/auth/login
Content-Type: application/json

{ "nomeUsuario": "admin", "senha": "123456" }

# DOCUMENTOS

###
# LISTAR DOCUMENTOS OK
GET {{baseUrl}}/documentos
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# BUSCAR DOCUMENTO EXISTENTE OK
GET {{baseUrl}}/documentos/2
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# BUSCAR DOCUMENTO INEXISTENTE OK
GET {{baseUrl}}/documentos/999999
Authorization: Bearer {{loginAdmin.response.body.token}}

###


# CRIAR DOCUMENTO VALIDO OK
POST {{baseUrl}}/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "tipo": "CPF",
  "numero": "12345678901",
  "dataEmissao": "2020-01-01"
}

###

# CRIAR DOCUMENTO COM ENUM INVALIDO
POST {{baseUrl}}/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "tipo": "CPF_INVALIDO",
  "numero": "12345678900",
  "dataEmissao": "2020-01-01"
}

###

# CRIAR DOCUMENTO COM DATA FUTURA OK
POST {{baseUrl}}/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "tipo": "CPF",
  "numero": "12345678900",
  "dataEmissao": "2099-01-01"
}

###

# CRIAR DOCUMENTO COM NUMERO VAZIO OK
POST {{baseUrl}}/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "tipo": "CPF",
  "numero": "",
  "dataEmissao": "2020-01-01"
}

###

# CRIAR DOCUMENTO COM dataEmissao VAZIO OK
POST {{baseUrl}}/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "tipo": "CPF",
  "numero": "12345678900",
  "dataEmissao": ""
}


###

# CRIAR DOCUMENTO SEM TIPO OK
POST {{baseUrl}}/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "numero": "12345678900",
  "dataEmissao": "2020-01-01"
}

###

# CRIAR DOCUMENTO SEM DATA OK
POST {{baseUrl}}/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "tipo": "CPF",
  "numero": "12345678900",
  "dataEmissao": ""
}

###

# CRIAR DOCUMENTO COM BODY VAZIO OK
POST {{baseUrl}}/documentos
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{}

###

# ATUALIZAR DOCUMENTO VALIDO OK
PUT {{baseUrl}}/documentos/1
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "tipo": "RG",
  "numero": "99887766",
  "dataEmissao": "2020-01-01"
}

###

# REMOVER DOCUMENTO EXISTENTE OK
DELETE {{baseUrl}}/documentos/3
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# REMOVER DOCUMENTO INEXISTENTE
DELETE {{baseUrl}}/documentos/999999
Authorization: Bearer {{loginAdmin.response.body.token}}