@baseUrl = http://localhost:8080/api

### Login ADMIN
# @name loginAdmin
POST http://localhost:8080/auth/login
Content-Type: application/json

{ "nomeUsuario": "admin", "senha": "123456" }

# EMAILS

###
# LISTAR EMAILS OK
GET {{baseUrl}}/emails
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# BUSCAR EMAIL EXISTENTE OK
GET {{baseUrl}}/emails/1
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# BUSCAR EMAIL INEXISTENTE OK
GET {{baseUrl}}/emails/999999
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# BUSCAR EMAIL COM ID INVALIDO 
GET {{baseUrl}}/emails/abc
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# CRIAR EMAIL VALIDO OK
POST {{baseUrl}}/emails
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "endereco": "teste@email.com"
}

###

# CRIAR EMAIL INVALIDO OK
POST {{baseUrl}}/emails
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "endereco": "email-invalido"
}

###

# CRIAR EMAIL VAZIO OK
POST {{baseUrl}}/emails
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "endereco": ""
}

###

# CRIAR EMAIL COM BODY VAZIO OK
POST {{baseUrl}}/emails
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{}

###

# CRIAR EMAIL COM JSON INVALIDO
POST {{baseUrl}}/emails
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "endereco": "teste@email.com",
}

###

# CRIAR EMAIL COM CONTENT TYPE ERRADO
POST {{baseUrl}}/emails
Content-Type: text/plain
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "endereco": "teste@email.com"
}

###

# ATUALIZAR EMAIL VALIDO
PUT {{baseUrl}}/emails/1
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "endereco": "novo@email.com"
}

###

# ATUALIZAR EMAIL INVALIDO
PUT {{baseUrl}}/emails/1
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "endereco": "abc"
}

###

# REMOVER EMAIL EXISTENTE
DELETE {{baseUrl}}/emails/1
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}


###

# REMOVER EMAIL INEXISTENTE OK
DELETE {{baseUrl}}/emails/999999
Authorization: Bearer {{loginAdmin.response.body.token}}