@baseUrl = http://localhost:8080/api

### Login ADMIN
# @name loginAdmin
POST http://localhost:8080/auth/login
Content-Type: application/json

{ "nomeUsuario": "admin", "senha": "123456" }

# MERCADORIAS

###

# LISTAR MERCADORIAS OK
GET {{baseUrl}}/mercadorias
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# BUSCAR MERCADORIA EXISTENTE OK
GET {{baseUrl}}/mercadorias/1
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# MOVIMENTAÇÃO DO ESTOQUE
PATCH {{baseUrl}}/mercadorias/1/estoque
Authorization: Bearer {{loginAdmin.response.body.token}}
Content-Type: application/json

{
  "quantidade": 1,
  "tipo": "SAIDA"
}


###

# BUSCAR MERCADORIA INEXISTENTE OK
GET {{baseUrl}}/mercadorias/999999
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# BUSCAR MERCADORIA COM ID INVALIDO
GET {{baseUrl}}/mercadorias/abc
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# BUSCAR MERCADORIA COM ID NEGATIVO
GET {{baseUrl}}/mercadorias/-1
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# BUSCAR MERCADORIA COM ID ZERO
GET {{baseUrl}}/mercadorias/0
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# CRIAR MERCADORIA VALIDA OK
POST {{baseUrl}}/mercadorias
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "Óleo 5W30",
  "descricao": "Óleo sintético motor",
  "valor": 45.90,
  "validade": "2026-12-31",
  "fabricacao": "2025-01-01",
  "quantidade": 10
}

###

# CRIAR MERCADORIA SEM BODY
POST {{baseUrl}}/mercadorias
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# CRIAR MERCADORIA JSON INVALIDO
POST {{baseUrl}}/mercadorias
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "Filtro de ar",
  "descricao": "Motor",
  "valor": 30.00,
  "validade": "2026-12-31",
  "fabricacao": "2025-01-01",
  "quantidade": 5,
}

###

# CRIAR MERCADORIA CONTENT TYPE ERRADO
POST {{baseUrl}}/mercadorias
Content-Type: text/plain
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "Pneu",
  "descricao": "Aro 15",
  "valor": 300.00,
  "validade": "2026-12-31",
  "fabricacao": "2025-01-01",
  "quantidade": 4
}

###

# CRIAR MERCADORIA SEM NOME (ERRO VALIDACAO)
POST {{baseUrl}}/mercadorias
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "",
  "descricao": "Teste",
  "valor": 50.00,
  "validade": "2026-12-31",
  "fabricacao": "2025-01-01",
  "quantidade": 5
}

###

# CRIAR MERCADORIA SEM VALOR (ERRO VALIDACAO)
POST {{baseUrl}}/mercadorias
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "Bateria",
  "descricao": "Carro",
  "validade": "2026-12-31",
  "fabricacao": "2025-01-01",
  "quantidade": 5
}

###

# CRIAR MERCADORIA VALIDADE PASSADA (ERRO VALIDACAO)
POST {{baseUrl}}/mercadorias
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "Item vencido",
  "descricao": "Teste",
  "valor": 10.00,
  "validade": "2020-01-01",
  "fabricacao": "2019-01-01",
  "quantidade": 5
}

###

# CRIAR MERCADORIA FABRICACAO FUTURA (ERRO VALIDACAO)
POST {{baseUrl}}/mercadorias
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "Item inválido",
  "descricao": "Teste",
  "valor": 10.00,
  "validade": "2026-12-31",
  "fabricacao": "2030-01-01",
  "quantidade": 5
}

###

# CRIAR MERCADORIA COM QUANTIDADE NEGATIVA (REGRA SERVICE)
POST {{baseUrl}}/mercadorias
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "Erro estoque",
  "descricao": "Teste",
  "valor": 10.00,
  "validade": "2026-12-31",
  "fabricacao": "2025-01-01",
  "quantidade": -5
}

###

# ATUALIZAR MERCADORIA VALIDA
PUT {{baseUrl}}/mercadorias/1
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "Óleo premium",
  "descricao": "Atualizado",
  "valor": 60.00,
  "validade": "2027-01-01",
  "fabricacao": "2025-01-01",
  "quantidade": 20
}

###

# ATUALIZAR MERCADORIA PARCIAL
PUT {{baseUrl}}/mercadorias/1
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "valor": 99.91
}

###

# ATUALIZAR MERCADORIA COM ID INVALIDO
PUT {{baseUrl}}/mercadorias/abc
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "Teste"
}

###

# ATUALIZAR MERCADORIA COM ID NEGATIVO
PUT {{baseUrl}}/mercadorias/-1
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
  "nome": "Teste"
}

###

# ATUALIZAR MERCADORIA SEM BODY
PUT {{baseUrl}}/mercadorias/1
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{}

###

# REMOVER MERCADORIA VALIDA
DELETE {{baseUrl}}/mercadorias/1
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# REMOVER MERCADORIA INEXISTENTE
DELETE {{baseUrl}}/mercadorias/999999
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# REMOVER MERCADORIA ID INVALIDO
DELETE {{baseUrl}}/mercadorias/abc
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# REMOVER MERCADORIA ID NEGATIVO
DELETE {{baseUrl}}/mercadorias/-1
Authorization: Bearer {{loginAdmin.response.body.token}}

###

# REMOVER MERCADORIA ID ZERO
DELETE {{baseUrl}}/mercadorias/1
Authorization: Bearer {{loginAdmin.response.body.token}}
